### PR TITLE
issue #102: extra fields in kvp

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
So many parts doing same thing. Cleared up fields processing.

## ⚙️ Test Data and/or Report

```
$ curl --location --request GET 'http://localhost:8080/products?fields=ops:Label_File_Info.ops:md5_checksum' --header 'Accept: application/kvp+json'
{
  "summary":{"hits":17,"took":79,"start":0,"limit":100,"sort":[],"properties":["ops:Label_File_Info/ops:md5_checksum"]},
  "data":[    {
      "ops:Label_File_Info.ops:md5_checksum":"24bf73b1cc29677faa4f590121164f4e"    },
    {
      "ops:Label_File_Info.ops:md5_checksum":"e2eb335391dfc4d838c632667a921eaa"    },
    {
      "ops:Label_File_Info.ops:md5_checksum":"ab72eb17bac95af9194d63dc7b26da50"    }, ...snip... }

```

## ♻️ Related Issues

#102 
NASA-PDS/pds-api#134

### CODE REVIEW

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

Fixed. Ready for review then merge.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner ,

Thanks for the update.

With my test I have a weird result where a comma is missing between the properties.

See `curl --location --request GET 'http://localhost:8080/products?fields=pds:Bundle_Member_Entry.pds:lid_reference,pds:Bundle_Member_Entry.pds:member_status' \
--header 'Accept: application/kvp+json'`

The result is:
```
{
    "summary": {
        "hits": 1,
        "took": 31,
        "start": 0,
        "limit": 100,
        "sort": [],
        "properties": [
            "pds:Bundle_Member_Entry/pds:lid_reference",
            "pds:Bundle_Member_Entry/pds:member_status"
        ]
    },
    "data": [
        {
            "pds:Bundle_Member_Entry.pds:member_status": "[Primary, Primary, Primary, Secondary]"      "pds:Bundle_Member_Entry.pds:lid_reference": "[urn:nasa:pds:insight_rad:data_raw, urn:nasa:pds:insight_rad:data_calibrated, urn:nasa:pds:insight_rad:data_derived, urn:nasa:pds:insight_documents:document_hp3rad]"
        }
    ]
}
```

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

Fixed. Lets try again.

**Review by tloubrieu-jpl — APPROVED** [review]
That works, thanks Al

**Pull request merged**
