### PR TITLE
Pds api 110: unify the behavior of response building

### LINKED ISSUE #2: Manage relationships bundle-collection-product in API

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Brief summary of changes if not sufficiently described by commit messages.

## ⚙️ Test Data and/or Report
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests

## ♻️ Related Issues

- NASA-PDS/pds-api#110

### CODE REVIEW

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams @tdddblog 

Its finally in place. Needs testing which I will get to Wednesday probably. Let me know if you want to review it in the breakout tomorrow.

**Review by tloubrieu-jpl — COMMENTED** [review]
Hi Al,

I am getting null pointer exception with the following requests:

curl --location --request GET 'http://localhost:8080/collections?limit=10' \
--header 'Accept: application/json'

and 

curl --location --request GET 'http://localhost:8080/products?only-summary=True' \
--header 'Accept: application/json'

I am using pds-api-javalib branch swaggerhub-pds_federated_api-pds-api-110-4

**Review by jordanpadams — COMMENTED** [review]
@al-niessner in the API spec, shouldn't this:
```
        application/csv+text:
           schema:
            $ref: '#/components/schemas/wyriwygProduct'
```

be this?
```
        text/csv:
           schema:
            $ref: '#/components/schemas/wyriwygProduct'
```

also I'm guessing `wyriwygProduct` is just a placeholder for those other inwork response formats?

**Comment by al-niessner** [comment]
Can change application/cvs+text to text/cvs at any time.

WYRIWIG - What You Request Is What You Get. Stolen from WYSIWIG editors. If
you want a better name, make it up and it can be changed.

**Comment by al-niessner** [comment]
That is the right javalib branch. I do not get a null pointer exception.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner , do you use a specific branch for the csv development ? If not you should branch off of this branch pds-api-110 to create a new branch for the CSV development so that this pds-api-110 stays stable for the tests.

Thanks

**Comment by al-niessner** [comment]
Sorry, forgot to create a new branch. I will do that for te webmvcc portion.

**Comment by al-niessner** [comment]
> Hi @al-niessner ,
> 
> I am getting null pointer exception with the following requests:
> 
> curl --location --request GET 'http://localhost:8080/collections?limit=10' --header 'Accept: application/json'
> 
> and
> 
> curl --location --request GET 'http://localhost:8080/products?only-summary=True' --header 'Accept: application/json'
> 
> I am using pds-api-javalib branch swaggerhub-pds_federated_api-pds-api-110-4

@tloubrieu-jpl 

This is not due to my changes. The input coming in from the curl makes q null. The search request builder is unmodified so the problem may be inherited from the main branch.

First, I added these two log lines:

```
        	log.debug("the input query string: " + String.valueOf(q));
        	log.debug("the context query string: " + String.valueOf(context.getQueryString()));
```

and produce this result:

```
2021-11-15 18:32:23.258 DEBUG 54 --- [0.3-8080-exec-1] g.n.p.a.e.c.MyProductsApiBareController  : the input query string: null
2021-11-15 18:32:23.258 DEBUG 54 --- [0.3-8080-exec-1] g.n.p.a.e.c.MyProductsApiBareController  : the context query string: null
```

Second, I went back to the main branch to test it. It works fine because somewhere it is translating the null to "". Going to update for that and see if it works.

**Comment by tloubrieu-jpl** [comment]
Thanks @al-niessner

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Fixed up the curl. Please try again or continue with review.

**Review by tloubrieu-jpl — APPROVED** [review]
Good to go, no much time to look at the details but that worked with my tests

**Pull request merged**
