### PR TITLE
Latest and all products

### PR DESCRIPTION
**Pull request by tdddblog**
See 
https://github.com/NASA-PDS/pds-api/issues/74
https://github.com/nasa-pds/pds-api/issues/95
https://github.com/NASA-PDS/pds-api/issues/107

NOTE: You have to build and install (mvn install) `https://github.com/NASA-PDS/pds-api-javalib/pull/8` before building this project.

### CODE REVIEW

**Review by jordanpadams — APPROVED** [review]
looks good to me. @jimmie can you take a quick peak as well?

**Comment by jordanpadams** [comment]
@tdddblog actually after looking at the OpenAPI updates, should we add separate endpoints for `bundles/{lid}` or rename `{lidvid}` to `{identifier}` and describe in the description what we mean by identifier? `bundles/{lidvid}/latest` and `bundles/{lidvid}/all` doesn't really make sense since `lidvid` implies a version is supplied.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl thoughts ☝️

**Comment by tdddblog** [comment]
@jordanpadams, @tloubrieu-jpl, I don't think you could have both `bundles/{lid}` and `bundles/{lidvid}` at the same time. They will be mapped to the same URL pattern. I think we should rename `{lidvid}` to `{identifier}`.

**Comment by jordanpadams** [comment]
@tdddblog sounds good. i will create a new ticket for that to address it when we can

**Comment by jordanpadams** [comment]
Merging the changes since I think they look ok. @tloubrieu-jpl it would be good if you could review this as well in case there is anything I am missing. we can create new tickets if there is specific refactoring your are looking for

**Pull request merged**
