### PR TITLE
Full-text / keyword search

### PR DESCRIPTION
**Pull request by tdddblog**
**Summary**
See https://github.com/NASA-PDS/pds-api/issues/99

**Test instructions**
- Build and install latest pds-api-javalib (on "swaggerhub-pds_federated_api-keywords" branch if it is not merged into main)
- Build latest registry-api-service
- Build latest Harvest (on "keyword" branch if it is not merged into main)
- Build latest Registry Manager (on "keyword" branch if it is not merged into main)
- Delete old registry
- Create new Registry
- Harvest some data
- Load harvested data into registry with Registry Manager
- Search for some keywords from "title" or "description" fields.

### CODE REVIEW

**Comment by jordanpadams** [comment]
@tdddblog can you take a look at why the build is breaking? also can you resolve the merge conflict?

**Comment by tdddblog** [comment]
@jordanpadams The build is breaking because it needs latest changes from `pds-api-javalib` project.

**Comment by tdddblog** [comment]
@jordanpadams It was too hard to resolve all the conflicts. I had to redo my changes and create new pull request https://github.com/NASA-PDS/registry-api-service/pull/60
Can we expedite reviews of pull requests which require swagger spec changes to avoid complex merges.

**Comment by jordanpadams** [comment]
@tdddblog per one of our previous sprints, if a PR is sitting out there for a while, let's bring it to our attention at a Sprint meeting and we can do a real-time demo and walk-through of the changes in the breakout so we can merge it. @tloubrieu-jpl and I are just overwhelmed with PRs, so we need some help knowing when things are higher priority versus others

**Pull request closed without merging**
