### PR TITLE
Updates for CSV and KVP response formats

### LINKED ISSUE #2: Manage relationships bundle-collection-product in API

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Fixes these issues:

#88 
https://github.com/NASA-PDS/pds-api/issues/65
https://github.com/NASA-PDS/pds-api/issues/120
https://github.com/NASA-PDS/pds-api/issues/125

and requires this work:

https://github.com/NASA-PDS/registry-api-service/pull/80

## ⚙️ Test Data and/or Report
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests

### CODE REVIEW

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

Ready for review and merging. Fixes many of the fiddly stuff application types etc. 

1. Has the API for 110 been merged?
2. Does the API need to be update for the pds4+xml, cvs, etc?

**Review by tloubrieu-jpl — COMMENTED** [review]
Some comments as I test the new code:
- we don't need the list of properties in summary when Accept format is application/pds4+json because the syntax of the properties is meaningless and the user can not do anything with them in the format.
- in the csv output the strings should be enclosed between " because sometimes the string contains ',' 
- the application/csv format should be replaced with text/csv
- I was not able to make the fields parameter on the CSV format, for example request:

```
curl --location --request GET 'http://localhost:8080/products?fields=lidvid,product_class' \
--header 'Accept: application/csv'

```

It sounds like this part is broken since the following request does not work either:

`curl --location --request GET 'http://localhost:8080/products?fields=pds:Target_Identification.pds:name'`

- I was not able to make the Accept format application/pds4+xml or application/pds+xml or application/xml work
- I don't see the new accepted format in the swagger ui 
See 
image


I used pds-api-javalib branch `origin/swaggerhub-pds_federated_api-pds-api-110-4` to build the API service

That being said I will approve the pull request, I create a new ticket to work on the previous actions

**Review by tloubrieu-jpl — APPROVED** [review]

**Comment by al-niessner** [comment]
From @tloubrieu-jpl 

> we don't need the list of properties in summary when Accept format is application/pds4+json because the syntax of the properties is meaningless and the user can not do anything with them in the format.

The documentation at swagger says it should be there and so it is. This is really a simplicity/consistency of design issue. I understand that PDS-4 is a standard and requires a fixed set of fields making the summary list redundant. To have a consistent interface that reduces the code variations required to support a huge host of special instances, the code simply returns the list. Is it really all that insulting to the users to return it?

**Comment by al-niessner** [comment]
From @tloubrieu-jpl 

> in the csv output the strings should be enclosed between " because sometimes the string contains ','

Changed.

**Comment by al-niessner** [comment]
From @tloubrieu-jpl 
> the application/csv format should be replaced with text/csv
> I was not able to make the Accept format application/pds4+xml or application/pds+xml or application/xml work
> I don't see the new accepted format in the swagger ui

All updated on https://github.com/NASA-PDS/pds-api-javalib/pull/14 and swagger 0,5.0-SNAPSHOT. gut-n-paste is so much fun.

**Comment by al-niessner** [comment]
Well, that was really fun. Fixed the fields problem and it works now:

```
$ curl --location --request GET 'http://localhost:8080/products?fields=lid,lidvid' --header 'Accept: text/csv'
lid,lidvid
"urn:nasa:pds:izenberg_pdart14_meap","urn:nasa:pds:izenberg_pdart14_meap::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_eetable","urn:nasa:pds:izenberg_pdart14_meap:data_eetable::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_imagecube","urn:nasa:pds:izenberg_pdart14_meap:data_imagecube::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_tnmap","urn:nasa:pds:izenberg_pdart14_meap:data_tnmap::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:document","urn:nasa:pds:izenberg_pdart14_meap:document::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_eetable:ele_evt_12hr_orbit_2011-2012","urn:nasa:pds:izenberg_pdart14_meap:data_eetable:ele_evt_12hr_orbit_2011-2012::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_eetable:ele_evt_8hr_orbit_2012-2013","urn:nasa:pds:izenberg_pdart14_meap:data_eetable:ele_evt_8hr_orbit_2012-2013::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_eetable:ele_evt_8hr_orbit_2014-2015","urn:nasa:pds:izenberg_pdart14_meap:data_eetable:ele_evt_8hr_orbit_2014-2015::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:virs_cube_64ppd_h01np","urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:virs_cube_64ppd_h01np::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:virs_wavelengths","urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:virs_wavelengths::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:data_tnmap:thermal_neutron_map","urn:nasa:pds:izenberg_pdart14_meap:data_tnmap:thermal_neutron_map::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:document:grs_inst","urn:nasa:pds:izenberg_pdart14_meap:document:grs_inst::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:document:instrument_host","urn:nasa:pds:izenberg_pdart14_meap:document:instrument_host::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:document:mascs_inst","urn:nasa:pds:izenberg_pdart14_meap:document:mascs_inst::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:document:meap_spec","urn:nasa:pds:izenberg_pdart14_meap:document:meap_spec::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:document:mission","urn:nasa:pds:izenberg_pdart14_meap:document:mission::1.0"
"urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst","urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0"
```

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

I think that fixes all of the problems listed. There is a conflict on the pom.xml and the main seems to have drifted back to 0.4.2-SNAPSHOT from 0.5.0-SNAPSHOT. Not sure how to resolve it so I am leaving for you.

**Pull request merged**
